### ISSUE TITLE
Home Efficiency variance

### ISSUE THREAD

**Issue by vincep5** [ziebelje/beestat-issues#88] opened 2019-01-16 16:10 UTC
My graph for Home Efficiency looks a little odd.  It has a spike at the outdoor temp of 17F and says my house temp increased over 7F.  Is there a way to remove the highest and lowest data points that you use in the calculation of the line?  
I've only had my thermostat for a few months, so maybe it is just my data.

Also - my house is a split level and the upper level is usually 3-5 degrees warmer than the main level.  When my scheduled switches from Home to Sleep, it changes the active sensor from the main level to the upper level.  In the other graphs (your's and Ecobee's) it naturally shows that the indoor temp is rising.   Does this switch from Home to Sleep have any impact on the Home Efficiency graph?  Your help icon said that "looking at the rate of temperature change when your HVAC system is completely off"  Which might be true for my scenario.

**Comment by ziebelje** [comment] 2019-01-16 17:27
Looks like your Home Efficiency graph has come down with a case of "beta" sickness. It's awful when it happens, and is typically caused by carelessness and lack of planning. There's a cure, but it's a couple months away. I hope it survives.

But seriously...
That graph is indeed pretty rushed on my part. What it currently does is looks for all blocks of time in your thermostat history where both your HVAC system was off and the outdoor temperature was consistent. It then takes a sample using the beginning and ending indoor temperature. Then, all the samples for each outdoor temperature are averaged together to produce the dotted line. Finally, a linear trendline is slapped on top of it and the score is based on the slope of that line.

The reason for the spike at 17°F is simply lack of data. There may have been only one or two data points for that specific outdoor temperature, and any combination of things could be the cause for the apparent increase in temperature: Sunny afternoon, oven on, sensor in a bad location, etc. That's why I apply a linear trend - helps to account for those oddities. The graphs tend to get a little wild in regions where your HVAC system is on a lot because there's simply data to average.

Deciding what to do in these situations is actually what I've been focused on for the past few days. [I wrote a post on my Patreon](https://www.patreon.com/posts/reworking-23970517) that goes into a little more detail about the reworked algorithm. I ran it on your thermostat and the results, unfortunately, still suck. I'll email you the graph and be sure to use your thermostat as one of my test cases. I think that, ultimately, the main issue you're facing is lack of data. To get a really good trendline you need solid data between roughly 40°F-80°F. I'll be working more to try and improve the results when I have less data. 

Also, your change from home to sleep will affect the graph a bit, but not too much. Everything is always averaged together. So you'll get a better temperature response in the winter during sleep, and a worse response all other times. It'll all average together and give you something that represents your home as close as possible. The indoor temperature I use when building the graph is the one that is displayed on your thermostat.

**Comment by ziebelje** [comment] 2019-03-05 19:16
Closing this as the results are significantly improved in 1.3. Thanks for all your help!

**Closed by ziebelje** 2019-03-05 19:16 UTC
Labels: ❔ Question
