### ISSUE TITLE
Missing custom schedules

### ISSUE THREAD

**Issue by sup-one** [ziebelje/beestat-issues#65] opened 2018-11-05 15:33 UTC
Great update.

In the Recent Activity graph I can see the Home and Sleep schedules but all of my custom schedules are missing (blank gaps).

![living room - recent activity](https://user-images.githubusercontent.com/42840882/48008090-fb6b1900-e0e6-11e8-810f-df04cd762747.png)

**Comment by ziebelje** [comment] 2018-11-05 15:48
I think that should be a relatively easy fix; thanks for reporting!

**Comment by ziebelje** [comment] 2018-11-08 12:48
Custom events now show up properly. This will go live with beestat 1.21 later this week.

![image](https://user-images.githubusercontent.com/3288812/48199630-b0d9de80-e32a-11e8-80d0-1a5ce843e573.png)

**Comment by sup-one** [comment] 2018-11-16 20:34
I've noticed that your site now displays Follow Me name that is not used in
my schedule.  I am using Home Eve but I see a comfort name Mid Day that is
displayed.  That comfort is never used in my current schedule (any day).

Oskar

**Comment by sup-one** [comment] 2018-11-19 15:22
Sorry for the delay.  Busy weekend.

My serial is 311003468569

Oskar

**Comment by sup-one** [comment] 2018-11-19 16:54
Today I've also noticed that the averaged temperature in the circle (using
thermostat temp and another sensor) shows continuously 22.0 while the
sensor and thermostat temps are 21.7.  The ecobee app shows the average
temp as 21.5.

Also the red and blue arrow that show if the sensor is above or below the
averaged temp do not correctly match the averaged temperature.

Oskar

**Comment by ziebelje** [comment] 2018-11-21 02:49
1. I see the issue with Follow me but I'm going to wait until next week to fix it. Currently I'm just displaying whatever your schedule is currently set to, so if you change your schedule it will actually go change data in the past on this graph. This was a stop-gap until I switched servers and had the ability to sync the proper data from ecobee which was done a few days ago. An appropriate fix will happen next week so hold tight.
2. The bug with the averages and arrows is fixed and will go live tonight or tomorrow. That was caused by splitting something like "21.7" into two parts > "22" and ".7" (notice the incorrect rounding of 21 to 22).

I will close this issue next week when I switch the Recent Activity graph to use the correct Follow Me data.

**Comment by ziebelje** [comment] 2018-12-04 02:14
Sorry for the delay; this is now fixed!

**Comment by vincep5** [comment] 2018-12-04 15:31
The issue with incorrect Follow Me name (custom climate) is still there for me

**Comment by ziebelje** [comment] 2018-12-04 15:33
(╯°□°）╯︵ ┻━┻

@vincep5, what's your thermostat ID? You can email it to contact@beestat.io if you like. I'll take a closer look.

**Comment by ziebelje** [comment] 2018-12-05 03:01
The previous fix only half-fixed the issue; it was showing the most recently added comfort profile any time it was not one of the standard ones. I now fully-fixed this issue.

**Closed by ziebelje** 2018-12-05 03:01 UTC
Labels: 🐞 Bug
