### ISSUE TITLE
Generating Efficiency profile never loads

### ISSUE THREAD

**Issue by beeafriend** [ziebelje/beestat-issues#75] opened 2018-11-16 23:28 UTC
Using the web browser and for my Thermostat that I've had on for a year it will not generate the efficiency profile.  It did download the data initially but it just spins at that part.

**Comment by beeafriend** [comment] 2018-11-17 01:10
Just sent you an e-mail.  Thanks!

**Comment by ziebelje** [comment] 2018-11-17 02:39
This is now fixed. It was caused by me initializing some values improperly on all the thermostats which in turn caused that graph to think it didn't have enough data to generate.

**Closed by ziebelje** 2018-11-17 02:39 UTC
